---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Teleport.
  ansible.builtin.package:
    name: "{{ teleport_package }}"
    state: "{{ teleport_package_state }}"

- include_tasks: config.yml
  when: teleport_create_config | bool

- name: Ensure Teleport is started and enabled at boot.
  ansible.builtin.service:
    name: teleport
    state: started
    enabled: true
