---
- name: Reload_Teleport
  become: yes
  systemd:
    name: "teleport"
    state: "reloaded"
    daemon_reload: yes
    enabled: yes
  when: teleport_control_systemd

- name: Restart Teleport
  become: yes
  systemd:
    name: "teleport"
    state: "restarted"
    daemon_reload: yes
    enabled: yes
  when: teleport_control_systemd